#!/usr/bin/env bash

# $1 is a required argument
if [ "$1" = "" ]
then
  echo "Usage: $0 \"<YouTube_URL>\""
  exit 1
fi

YouTube_URL="$1"
music_dir="$HOME/Music/"

# ~/Music/ doesn't exist
if [ -d "$music_dir" ]; then
  echo "Notification: ${music_dir} exists!"
else
  echo "Notification: ${music_dir} was not found in $HOME directory."
  mkdir $music_dir
fi

cd $music_dir

# Add --embed-thumbnail flag for music cover! (only mp3 format)
youtube-dl --audio-quality 160K --restrict-filenames --extract-audio --audio-format opus -o "%(title)s.%(ext)s" $YouTube_URL
